"""Emit the wire-format cases that the JavaScript side decodes.

Written as a test so it runs with the suite: if the encoder changes and the
cases are not regenerated, the JS test decodes stale bytes and the drift goes
unnoticed. Generating them here keeps the two halves in step by construction.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

import numpy as np

from mdqm.dqm import framing

OUT = Path(__file__).resolve().parent / "js" / "framing-cases.json"


def _case(name, counts, edges, entries, array_type, payload=None):
    if payload is None:
        payload = framing.encode_histogram(counts, edges, entries)
    return {
        "name": name,
        "payload_b64": base64.b64encode(payload).decode(),
        "n_bins": [n - 2 for n in reversed(counts.shape)],
        "low_edge": [float(e[0]) for e in edges],
        "high_edge": [float(e[1]) for e in edges],
        "entries": entries,
        "array_type": array_type,
        "counts_flat": [float(v) if "Float" in array_type else int(v)
                        for v in counts.ravel()],
    }


def build_cases() -> list[dict]:
    rng = np.random.default_rng(7)
    cases = []

    # 1D integer: the ordinary amplitude-spectrum shape.
    counts = rng.integers(0, 5000, size=202, dtype=np.uint32)
    cases.append(_case("1D u32 histogram", counts, [(0.0, 1.0)], 123456, "Uint32Array"))

    # 2D integer: persistence. Deliberately non-square so a transposed encoding
    # cannot pass by accident.
    counts2 = rng.integers(0, 900, size=(112, 258), dtype=np.uint32)
    cases.append(_case("2D u32 histogram (non-square)", counts2,
                       [(0.0, 1024.0), (-1.0, 0.1)], 987654321, "Uint32Array"))

    # Float variants, for anything that is a mean rather than a count.
    f1 = rng.normal(size=52).astype(np.float32)
    cases.append(_case("1D f32 histogram", f1, [(-5.0, 5.0)], 4242, "Float32Array"))

    f2 = rng.normal(size=(12, 22)).astype(np.float32)
    cases.append(_case("2D f32 histogram", f2, [(0.0, 360.0), (0.0, 1.0)], 7, "Float32Array"))

    # A single bin, the smallest legal histogram: exercises the alignment
    # padding with almost no data after it.
    tiny = np.array([1, 2, 3], dtype=np.uint32)
    cases.append(_case("1D u32, one real bin", tiny, [(0.0, 1.0)], 6, "Uint32Array"))

    # u64 counters, through the Hist classes that own them: they must reach
    # musip's decoder as f64 with every count exact, including ones past 2**32
    # that a u32 encoding would have wrapped.
    from mdqm.dqm.hist import Axis, Hist1D, Hist2D

    h1 = Hist1D("u64", Axis(6, 0.0, 6.0), dtype=np.uint64)
    c1 = rng.integers(0, 1000, size=8).astype(np.uint64)
    c1[3] = 2**40 + 7
    h1.add_counts(c1, entries=12345678901)
    cases.append(_case("1D u64 histogram as f64", h1.counts, [(0.0, 6.0)], h1.entries,
                       "Float64Array", payload=h1.encode()))

    h2 = Hist2D("u64_2d", Axis(5, -1.0, 1.0), Axis(3, 0.0, 30.0), dtype=np.uint64)
    c2 = rng.integers(0, 1000, size=(5, 7)).astype(np.uint64)
    c2[2, 4] = 2**33
    h2.add_counts(c2)
    cases.append(_case("2D u64 histogram as f64 (non-square)", h2.counts,
                       [(-1.0, 1.0), (0.0, 30.0)], h2.entries,
                       "Float64Array", payload=h2.encode()))

    return cases


def test_generate_framing_cases():
    """Regenerate the fixtures the JavaScript cross-check consumes."""
    cases = build_cases()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps({
        "_doc": "Generated by tests/generate_framing_cases.py. Decoded by "
                "tests/js/framing.test.js using musip's unmodified decoder.",
        "cases": cases,
    }, indent=1))
    assert OUT.is_file()
    assert len(cases) >= 4


def test_python_decodes_its_own_encoding():
    """The self-consistency half, which the JS test deliberately does not cover."""
    for case in build_cases():
        payload = base64.b64decode(case["payload_b64"])
        got = framing.decode_histogram(payload)
        assert got["n_bins"] == case["n_bins"], case["name"]
        assert got["entries"] == case["entries"], case["name"]
        assert [round(v, 6) for v in got["low_edge"]] == \
               [round(v, 6) for v in case["low_edge"]], case["name"]


def test_envelope_round_trip():
    payload = b"\x01\x02\x03"
    size, tag, body = framing.parse_envelope(framing.envelope(framing.TAG_HIST, payload))
    assert size == framing.HEADER_SIZE + len(payload)
    assert tag == b"hist"
    assert body == payload


def test_envelope_rejects_a_wrong_length_tag():
    import pytest
    with pytest.raises(ValueError):
        framing.envelope(b"toolong", b"")
    with pytest.raises(ValueError):
        framing.envelope(b"ab", b"")


def test_a_short_read_is_reported_not_guessed():
    """The page retries on truncation, so this has to fail loudly."""
    import pytest
    with pytest.raises(ValueError):
        framing.parse_envelope(b"\x00\x01")
